name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up JDK (Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'
          ndk: '21.1.6352462'

      # 4. Cache Gradle dependencies to speed up the build
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # 5. Run Detekt for static code analysis
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: false  # Fail the build if Detekt finds issues

      # 6. Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: false

      # 7. Run Android instrumented tests
      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest
        continue-on-error: false

      # 8. Generate test coverage report
      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport
        continue-on-error: false

      # 9. Upload test reports and coverage results
      - name: Upload Test and Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports/
