name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run Detekt Analysis
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Upload Detekt Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: app/build/reports/detekt/

  test:
    runs-on: ubuntu-latest
    needs: build  # Pour s'assurer que le job de build est terminé avant de commencer les tests

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30  # Utilise la version API souhaitée
          target: google_apis
          arch: x86_64
          profile: pixel  # Modèle de l'émulateur
          emulator-options: "-no-window -no-boot-anim"
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Run Unit Tests and Coverage
        run: ./gradlew clean testDebugUnitTest jacocoTestReport

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html/

      - name: Check JaCoCo Coverage
        run: |
          # Extraction du taux de couverture depuis le rapport JaCoCo HTML
          coverage=$(grep -oP 'line-rate="\K[0-9.]*' app/build/reports/jacoco/jacocoTestReport/html/index.html)
          echo "Current coverage: $coverage"
          
          # Comparer le taux de couverture à un seuil de 90%
          if (( $(echo "$coverage < 0.90" | bc -l) )); then
            echo "Coverage is below 90%, failing the build."
            exit 1
          fi