name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
        target: [default, google_apis]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          sudo update-alternatives --config java
          java -version  # Verify Java 17 is being used

      - name: Set JAVA_HOME to Java 17
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME"  # Check the JAVA_HOME path

      - name: Verify Java version in the environment
        run: java -version  # Confirm Java 17 is being used

      - name: Set Gradle to use Java 17
        run: |
          echo "org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64" >> gradle.properties
          cat gradle.properties  # Verify the property was added

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Cache AVD files
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching (if necessary)
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedCheck
