name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 3. Set up JDK (Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 4. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'
          ndk: '21.1.6352462'

      # 5. Cache Gradle dependencies to speed up the build
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # 6. Run Detekt for static code analysis
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: false

      # 7. Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: false

  android-tests:
    runs-on: macos-latest
    needs: build

    steps:
      # 1. Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Set up JDK (Java 11 for emulator compatibility)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      # 3. Run Android instrumented tests on emulator
      - name: Run Android Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest
          disable-animations: true

  coverage:
    runs-on: ubuntu-latest
    needs: [build, android-tests]

    steps:
      # 1. Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Generate JaCoCo coverage report
      - name: Generate Coverage Report
        run: ./gradlew jacocoTestReport
        continue-on-error: false

      # 3. Upload test and coverage reports
      - name: Upload Test and Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports/
